const ids = {
    LOGIN_SCREEN : 'loginScreen',
    BOARD_USER : 'user',
    BOARD_CLOCK : 'clock',
    BOARD : 'board',
    CELL : 'c',
    SET_CONTROLS : 'setControls',
    SET_SUDOKU_BTN : 'setBtn',
    VALIDATE_BTN : 'validateBtn',
    RATE_BTN : 'rateBtn',
    NOTE_BTN : 'notebtn',
    HINT_BTN : 'hintBtn',
    SOLUTION_BTN : 'showSolution',
    MENU_NEW_BTN : 'newBtn',
    MENU_VISUALISER_BTN : 'visBtn',
    MENU_INSTRUCTIONS_BTN : 'insBtn',
    MENU_MOB : 'mobMenu',
    UNDO_BTN : 'undo',
    REDO_BTN : 'redo',
    RESET_BTN : 'reset',
    CLEAR_BTN : 'clearBtn',
    RESET_BTN : 'reset',
    MAIN_CONTROLS : 'mainControls',
    INPUT_NUM : 'inputNum',
    NUMPAD_WRAP : 'numpadWrap',
    NUMPAD : 'numpad',
    TIMER: 'timer',
    HOURS: 'hrs',
    MINUTES: 'mts',
    SECONDS: 'scs',
    MAIN_MENU: 'menuMain',
    BACKDROP: 'BACKDROP',
    USER_LOGO : 'userLogo',
    USER_MENU : 'userMenu',
    USER_DISPLAY: 'USER_DISPLAY',
    STATS_LOGOUT : 'logout',
    STATS_SAVE : 'saveGame',
    STATS_CLOSE : 'closeStats',
    STATS : 'stats',
    STATS_GAME : 'statsGeme',
    STATS_OVERAL : 'statsOveral',
    MENU_RANDOM_BTN : 'random',
    MENU_SETSUDOKU_BTN : 'set',
    MENU_GENERATE_BTN : 'gen',
    MENU_BACK_BTN : 'toMain',
    PUZZLES_MENU : 'menuPuzzle',
    GEN_LIMITER : 'limit',
    GEN_RUN_BTN : 'generate',
    GEN_PLAY_BTN : 'GEN_PLAY_BTN',
    VIS_SPEED_LAB : 'sliderLabel',
    VIS_SPEED_SLIDER : 'speed',
    VIS_RUN_BTN : 'runBtn',
    VIS_GEN_BTN : 'genBtn',
    WIN_DIALOGE : 'winDialog',
    WIN_NEW : 'WIN_NEW',
    WIN_EXIT : 'WIN_EXIT',
    INSTRUCTIONS : 'instructions',
    SPINNER : 'spinner',
    FORM_EMAIL : 'inputEmail',
    FORM_PASS : 'inputPassword',
    FORM_LOGIN_BTN : 'loginButton',
    FORM_SIGNUP_BTN : 'signupButton',
    FORM_GUEST_BTN : 'guestButton',
    FORM_INPUTS : 'formInputs',
    FORM : 'signInForm',
    FORM_ERROR : 'formErrorDisplay',
    INS_CLOSE : 'INS_CLOSE',
    CONTROLS_WRAP : 'CONTROLS_WRAP',
    BOARD_WRAP : 'BOARD_WRAP',
    WRAP : 'WRAP',
    MENU_WRAP :' MENU_WRAP',
    HEADER : 'HEADER'
}


