const ids = {
    LOGIN_SCREEN : 'loginScreen',
    BOARD : 'board',
    CELL : 'c',
    SET_CONTROLS : 'setControls',
    SET_SUDOKU_BTN : 'setBtn',
    VALIDATE_BTN : 'validateBtn',
    RATE_BTN : 'rateBtn',
    NOTE_BTN : 'notebtn',
    HINT_BTN : 'hintBtn',
    SOLUTION_BTN : 'showSolution',
    MENU_NEW_BTN : 'newBtn',
    MENU_VISUALISER_BTN : 'visBtn',
    MENU_INSTRUCTIONS_BTN : 'insBtn',
    MENU_MOB : 'mobMenu',
    UNDO_BTN : 'undo',
    REDO_BTN : 'redo',
    RESET_BTN : 'reset',
    CLEAR_BTN : 'clearBtn',
    RESET_BTN : 'reset',
    MAIN_CONTROLS : 'mainControls',
    INPUT_NUM : 'inputNum',
    NUMPAD_WRAP : 'numpadWrap',
    NUMPAD : 'numpad',
    TIMER: 'timer',
    HOURS: 'hrs',
    MINUTES: 'mts',
    SECONDS: 'scs',
    MAIN_MENU: 'menuMain',
    MAIN_MENU_WRAP: 'mainMenuWrap',
    USER_LOGO : 'userLogo',
    USER_MENU : 'userMenu',
    STATS_LOGOUT : 'logout',
    STATS_SAVE : 'saveGame',
    STATS_CLOSE : 'closeStats',
    STATS : 'stats',
    STATS_GAME : 'statsGeme',
    STATS_OVERAL : 'statsOveral',
    MENU_RANDOM_BTN : 'random',
    MENU_SETSUDOKU_BTN : 'set',
    MENU_GENERATE_BTN : 'gen',
    MENU_BACK_BTN : 'toMain',
    PUZZLES_MENU : 'menuPuzzle',
    GEN_LIMITER : 'limit',
    GEN_RUN_BTN : 'generate',
    GEN_PLAY_BTN : 'GEN_PLAY_BTN',
    VIS_SPEED_LAB : 'sliderLabel',
    VIS_SPEED_SLIDER : 'speed',
    VIS_RUN_BTN : 'runBtn',
    VIS_GEN_BTN : 'genBtn',
    WIN_DIALOGE : 'winDialog',
    WIN_NEW : 'WIN_NEW',
    WIN_EXIT : 'WIN_EXIT',
    INSTRUCTIONS : 'instructions',
    SPINNER : 'spinner',
    FORM_EMAIL : 'inputEmail',
    FORM_PASS : 'inputPassword',
    FORM_LOGIN_BTN : 'loginButton',
    FORM_SIGNUP_BTN : 'signupButton',
    FORM_GUEST_BTN : 'guestButton',
    FORM_INPUTS : 'formInputs',
    FORM : 'signInForm',
    FORM_ERROR : 'formErrorDisplay',
    INS_CLOSE : 'INS_CLOSE',
    CONTROLS_WRAP : 'CONTROLS_WRAP',
    BOARD_WRAP : 'BOARD_WRAP',
    WRAP : 'WRAP',
    MENU_WRAP :' MENU_WRAP',
    HEADER : 'HEADER'
}

const classNames = {
    BOX : 'Box',
    BOARD : 'Board',
    CELL : 'Cell',
    HIGHLIGHT : 'Higlight',
    NOTE_MODE_ON : 'NoteOn',
    NOTE_CELL : 'NoteCell',
    CONTROLS : 'Controls',
    SET_MOBILE : 'SetMobile',
    BTN_NORMAL : 'BtnNormal',
    WIDGET : 'Widget',
    BTNS_GAME : 'BtnsGame',
    BTNS_STEPP : 'BtnsStepp',
    BTNS_MAIN :  'BtnsWrap',
    BTNS_USER : 'UserBtns',
    ICON_WRAP : 'IconWrap',
    ICON : 'Icon',
    INPUT_NUM : 'InputNum',
    NUMPAD: 'Numpad',
    TIMER: 'Timer',
    NAVIGATION_BTN : 'NavBtn',
    MAIN_MENU : 'MainMenu',
    USER_MENU : 'UserMenu',
    BTN_STATS : 'StatsButton',
    STATS_TITLE : 'StatsTitle',
    STATS : 'Stats',
    STAT : 'Stat',
    STATS_WINDOW : 'StatsDisplay',
    GEN_LIMITER : 'InputGenLimit',
    GEN_RUN_BTN : 'GenBtn',
    LABEL : 'Label',
    WRAP_CTRL_INPUT: 'WrapCtrlInput',
    VIS_SPEED_SL : 'VisSpeedSlider',
    WIN_WINDOW : 'Winner',
    WIN_RANKING : 'Ranking',
    WIN_BTN : 'WinBtn',
    BACKDROP : 'Backdrop',
    INSTRUCTIONS : 'Instructions',
    SPINNER : 'Spinner',
    LOG_TITLE : 'Title',
    LOG_TITLE_LETTER : 'TitleLetter',
    LOG_TITLE_LARGE : 'TitleLetterLarge',
    LOG_SCREEN : 'LoginScreen',
    LOG_FORM : 'LoginForm',
    FORM_BTN : 'FormButton',
    FORM_INPUT : 'FormInput',
    FORM_BTN_WRAP : 'FormButtonsWrap',
    FORM_INPUT_WRAP : 'FormInputWrap',
    ADDED : 'Added',
    INPUT_INVALID : 'InvalidInput',
    INPUT_VALID : 'ValidInput',
    MESSAGE : 'Message',
    NUMBER : 'Number',
    NUMBER_INVALID : 'Invalid',
    VISUALISE : 'Visualise',
    MENU_WRAP : 'MenuWrap',
    MOB_MENU : 'MobMenu',
    BOARD_WRAP : 'BoardWrap',
    wrap : 'wrap',
    GIT_HUB : 'GitHub'
}
